ant/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls'), name='users'),
    path('projects/', include('projects.urls'), name='projects'),
    path('', include('projects.urls')),
]

users/urls.py
from django.urls import re_path, path
from .views import org_register, stu_register, org_login, stu_login, logout, \
    edit_info_stu, edit_profile_stu, edit_info_org, edit_profile_org, \
    get_project_list, dashboard

app_name="users"

urlpatterns = [
    path('', dashboard, name='register_org'),
    re_path(r'^register_org/$', org_register, name='register_org'),
    re_path(r'^register_stu/$', stu_register, name='register_stu'),
    re_path(r'^login_org/$', org_login, name='login_org'),
    re_path(r'^login_stu/$', stu_login, name='login_stu'),
    re_path(r'^logout/$', logout, name='logout'),
    re_path(r'^edit_info_stu/(?P<id>\d+)/$', edit_info_stu, name='edit_info_stu'),
    re_path(r'^edit_profile_stu/(?P<id>\d+)/$', edit_profile_stu, name='edit_profile_stu'),
    re_path(r'^edit_info_org/(?P<id>\d+)/$', edit_info_org, name='edit_info_org'),
    re_path(r'^edit_profile_org/(?P<id>\d+)/$', edit_profile_org, name='edit_profile_org'),
    # re_path(r'^profile_list/$', profile_list, name='profile_list'),
    re_path(r'^project_list/$', get_project_list, name='project_list'),
]

users/models.py
from django.db import models
from django.contrib.auth.hashers import make_password, check_password


class Organization(models.Model):
    username = models.CharField(max_length=20)
    password = models.CharField(max_length=128)
    phone = models.CharField(max_length=20)
    email = models.EmailField()

    def __str__(self):
        return self.username

    def save(self, *args, **kwargs):
        self.password = set_password(self.password)
        super(Organization, self).save(*args, **kwargs)


class Student(models.Model):
    username = models.CharField(max_length=20)
    password = models.CharField(max_length=128,)
    phone = models.CharField(max_length=20)
    email = models.EmailField()

    def __str__(self):
        return self.username

    def save(self, *args, **kwargs):
        self.password = set_password(self.password)
        super(Student, self).save(*args, **kwargs)


def set_password(password):
    password_hash = make_password(password)
    return password_hash


def check_password_hash(password, password_hash):
    return check_password(password, password_hash)

users/forms.py
from .models import Organization, Student
from django import forms


class OrgRegisterForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = '__all__'

        css = {'class': "form-control", 'size': "35", 'maxlength': "60"}
        widgets = {
            'username': forms.TextInput(attrs=css),
            'password': forms.PasswordInput(attrs=css),
            'phone': forms.TextInput(attrs=css),
            'email': forms.EmailInput(attrs=css),
            'logo': forms.FileInput(attrs=css),
        }


class StuRegisterForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = '__all__'

        # css = {'class': "", 'size': "35", 'maxlength': "60"}
        widgets = {
            'username': forms.TextInput(attrs={'placeholder':'username', 'class': "form-control", 'size': "35", 'maxlength': "60"}),
            'password': forms.PasswordInput(attrs={'placeholder':'password', 'class': "form-control", 'size': "35", 'maxlength': "60"}),
            'school': forms.TextInput(attrs={'placeholder':'school', 'class': "form-control", 'size': "35", 'maxlength': "60"}),
            'email': forms.EmailInput(attrs={'placeholder':'email', 'class': "form-control", 'size': "35", 'maxlength': "60"}),
            'phone': forms.TextInput(attrs={'placeholder':'phone', 'class': "form-control", 'size': "35", 'maxlength': "60"}),
        }

class StuLoginForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = ['username', 'password']

        # css = {'class': "", 'size': "35", 'maxlength': "60"}
        widgets = {
            'username': forms.TextInput(attrs={'placeholder':'username', 'class': "form-control", 'size': "35", 'maxlength': "60"}),
            'password': forms.PasswordInput(attrs={'placeholder':'password', 'class': "form-control", 'size': "35", 'maxlength': "60"}),
        }


class OrgLoginForm(forms.ModelForm):
    class Meta:
        model = Organization
        fields = ['username', 'password']

        # css = {'class': "", 'size': "35", 'maxlength': "60"}
        widgets = {
            'username': forms.TextInput(attrs={'placeholder':'username', 'class': "form-control", 'size': "35", 'maxlength': "60"}),
            'password': forms.PasswordInput(attrs={'placeholder':'password', 'class': "form-control", 'size': "35", 'maxlength': "60"}),
        }

users/views.py
from django.shortcuts import render, HttpResponse, redirect, reverse
from django.contrib import messages
from django.http import HttpResponseRedirect
from .forms import OrgRegisterForm, StuRegisterForm, StuLoginForm, OrgLoginForm
from .models import Organization, Student
from profiles.forms import StuProfileForm, OrgProfileForm
from .models import set_password, check_password_hash
from profiles.models import StuProfile, OrgProfile, Profile_relationship
from projects.models import Project
# Create your views here.

def org_register(request):
    if request.method == 'POST':
        form = OrgRegisterForm(request.POST, request.FILES)
        if form.is_valid():
            username = form.cleaned_data['username']
            if len(Organization.objects.filter(username=username)) != 0:
                info = {'error': 'User Exists!'}
                return render(request, 'users/sign_up.html', info)
            else:
                password = form.cleaned_data['password']
                form.save()
                messages.success(request, 'Congratulations')
                return HttpResponseRedirect('/users')
    else:
        form = OrgRegisterForm()
    return render(request, 'users/sign_in.html', locals())

def stu_register(request):
    if request.method == 'POST':
        form = StuRegisterForm(request.POST, request.FILES)
        if form.is_valid():
            username = form.cleaned_data['username']
            if len(Student.objects.filter(username=username)) != 0:
                info = {'error': 'User Exists!'}
                return render(request, 'users/sign_up.html', info)
            else:
                password = form.cleaned_data['password']
                form.save()
                messages.success(request, 'Congratulations')
                return HttpResponseRedirect('/users')
    else:
        form = StuRegisterForm()
    return render(request, 'users/sign_up.html', locals())

def org_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        org = Organization.objects.filter(username=username).first()
        if org == None:
            messages.error(request, 'Username or Password may be incorrect')
            return render(request, 'users/sign_in.html', locals())
        if not check_password_hash(password, org.password):
            messages.error(request, 'Username or Password may be incorrect')
            return render(request, 'users/sign_in.html', locals())

        request.session['username'] = org.username
        request.session['id'] = org.id
        request.session['mark'] = 0
        messages.success(request, 'Welcome Back!')
        return HttpResponseRedirect('/users')
    else:
        form = OrgLoginForm()
    return render(request, 'users/sign_in.html', locals())

def stu_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        stu = Organization.objects.filter(username=username).first()
        if stu == None:
            messages.error(request, 'Username or Password may be incorrect')
            return render(request, 'users/sign_in.html', locals())
        if not check_password_hash(password, stu.password):
            messages.error(request, 'Username or Password may be incorrect')
            return render(request, 'users/sign_in.html', locals())

        #TODO: ENCRYPT THIS
        request.session['username'] = stu.username
        request.session['id'] = stu.id
        request.session['mark'] = 0
        messages.success(request, 'Welcome Back!')
        return HttpResponseRedirect('/users')
    else:
        form = StuLoginForm()
    return render(request, 'users/sign_in.html', locals())

def logout(request):
    request.session.flush()
    return redirect(reverse('projects:index'))

def edit_info_stu(request, id):
    # TODO: AUTH REQUIRED
    stu = Student.objects.get(id=id)
    if request.method == 'POST':
        username = request.POST.get('username')
        email = request.POST.get('email')
        phone = request.POST.get('phone')
        Student.objects.filter(id=id).update(username=username,
                                            email=email, phone=phone)
        messages.success(request, 'Edit Saved')
        return HttpResponseRedirect('/users/edit_info_stu/%s' % id, )
    return render(request, 'student/stu_info_edit.html', locals())


def edit_profile_stu(request, id):
    # TODO: AUTH REQUIRED
    profile = StuProfile.objects.filter(user_id=id).first()
    if request.method == 'POST':
        form = StuProfileForm(request.POST, instance=profile)
        if form.is_valid():
            try:
                form.save()
                messages.success(request, 'Edit Saved')
            except:
                form.cleaned_data['user_id'] = int(id)
                profile.objects.create(**form.cleaned_data)
                messages.success(request, 'Added')
    else:
        form = StuProfileForm(instance=profile)
    return render(request, 'student/stu_profile_edit.html', locals())


def edit_info_org(request, id):
    # TODO: AUTH REQUIRED
    org = Organization.objects.get(id=id)
    if request.method == 'POST':
        username = request.POST.get('username')
        email = request.POST.get('email')
        phone = request.POST.get('phone')
        Student.objects.filter(id=id).update(username=username,
                                            email=email, phone=phone)
        messages.success(request, 'Edit Saved')
        return HttpResponseRedirect('/users/edit_info_stu/%s' % id, )
    return render(request, 'student/org_info_edit.html', locals())


def edit_profile_org(request, id):
    # TODO: AUTH REQUIRED
    profile = OrgProfile.objects.filter(user_id=id).first()
    if request.method == 'POST':
        form = OrgProfileForm(request.POST, instance=profile)
        if form.is_valid():
            try:
                form.save()
                messages.success(request, 'Edit Saved')
            except:
                form.cleaned_data['user_id'] = int(id)
                profile.objects.create(**form.cleaned_data)
                messages.success(request, 'Added')
    else:
        form = StuProfileForm(instance=profile)
    return render(request, 'organization/org_profile_edit.html', locals())

def get_project_list(request):
    # TODO: AUTH REQUIRED
    try:
        stu_id = int(request.session['id'])
        profile = StuProfile.objects.filter(user_id=stu_id).first()
        project_id_list = Profile_relationship.objects.filter(profile_id=profile.id)
        project_list = [Project.objects.filter(id=project_id.project_id)[0] for project_id in project_id_list]
    except:
        info = 'No Projects Avaliable'
    return render(request, 'student/get_project_list.html', locals())

def dashboard(request):
    return render(request, 'users/student-dashboard.html', locals())

templates/users/sign_in.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="/static/style.css">
    <title>ANT!</title>
  </head>
  <body>
    <header id="header">
      <div class="container-fluid head">
        <div class="row">
          <div class="col-1"></div>
          <div class="col">
            <img id="logo" class="img-fluid" src="/static/pictures/logo.png" alt="">
            <div class="container">
              <h1 class="display-4" style="margin: 0"><b>Ant</b></h1>
            <p style="margin: 0">Connect Student and Organisations togethers</p>
            </div>
          </div>
          <div class="col">
 <a type="button" class="btn btn-secondary home-btn" href="/users/register_stu/">Sign Up</a>
            <a type="button" class="btn btn-light home-btn" href="/users/login_stu/">Sign In</a>
          </div>
          <div class="col-1"></div>
        </div>
      </div>
    </header><!-- /header -->

    <nav class="navbar sticky-top navbar-light bg-light">
      <div class="container-fluid">
        <a class="navbar" href="/">Home</a>
        <a class="navbar" href="index.html">About Us</a>
        <a class="navbar" href="index.html">Benefit</a>
        <a class="navbar" href="index.html">Companies</a>
        <a class="navbar" href="index.html">Sucess Stories</a>
        <a class="navbar" href="index.html">Contact</a>
      </div>
    </nav>

    <main>
      <div class="container justify-content-center">
        <div class="col-2"></div>
        <div class="col">
          <div class="card">
          <h5 class="card-header">Sign In</h5>
          <div class="card-body">
                                                  <div style="font-family: 微软雅黑"><b>{{ info.error }}</b></div>

              <form action="{% url 'users:login_stu' %}" method="post"
                  enctype="multipart/form-data">
                  {% csrf_token %}
                {{ error }}
                {% for field in form %}
                       <div class="form-group">
                                {{ field }}<br>
                        </div>
                    {% endfor %}
                            <div class="height20"></div>
                            <input type="submit" class="btn btn-primary" id="btnSubmit"
                                   value="Submit">
            </form>
          </div>
        </div>
        <div class="col-2"></div>
      </div>
    </main>

    <footer class="fixed-bottom">
      <div class="container footer-signin">
        <div class="row">
          <div class="col-12 justify-content-center">
            <p style="text-align: center">Copyright 2019 | <a href="">Terms and Conditions</a> applied</p>
          </div>
        </div>
      </div>
    </footer>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

templates/users/sign_up.html
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport"
          content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet"
          href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
          crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="/static/style.css">
    <title>ANT!</title>
</head>
<body>
<header id="header">
    <div class="container-fluid head">
        <div class="row">
            <div class="col-1"></div>
            <div class="col">
                <img id="logo" class="img-fluid" src="/static/pictures/logo.png" alt="">
                <div class="container">
                    <h1 class="display-4" style="margin: 0"><b>Ant</b></h1>
                    <p style="margin: 0">Connect Student and Organisations
                        togethers</p>
                </div>
            </div>
            <div class="col">
 <a type="button" class="btn btn-secondary home-btn" href="/users/register_stu/">Sign Up</a>
            <a type="button" class="btn btn-light home-btn" href="/users/login_stu/">Sign In</a>
            </div>
            <div class="col-1"></div>
        </div>
    </div>
</header><!-- /header -->

<nav class="navbar sticky-top navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar" href="/">Home</a>
        <a class="navbar" href="index.html">About Us</a>
        <a class="navbar" href="index.html">Benefit</a>
        <a class="navbar" href="index.html">Companies</a>
        <a class="navbar" href="index.html">Sucess Stories</a>
        <a class="navbar" href="index.html">Contact</a>
    </div>
</nav>
<div class="container">
    <div class="row">
        <div class="col">
                                        <div style="font-family: 微软雅黑"><b>{{ info.error }}</b></div>
            <form {% if 'register_org' in request.path %}
                  action="{% url 'users:register_org' %}" {% else %}
                  action="{% url 'users:register_stu' %}"  {% endif %}method="post"
                  enctype="multipart/form-data">
                {% csrf_token %}
                {{ error }}
                    {% for field in form %}
                       <div class="form-group">
                                {{ field }}<br>
                        </div>
                    {% endfor %}
                            <div class="height20"></div>
                            <input type="submit" class="btn btn-primary" id="btnSubmit"
                                   value="Submit">
            </form>
            {#          <form>#}
            {#            <div class="form-group">#}
            {#              <input type="text" class="form-control" name="name" placeholder="Name">#}
            {#            </div>#}
            {#            <div class="form-group">#}
            {#              <input type="email" class="form-control" id="exampleFormControlInput1" placeholder="Email: example@gmail.com">#}
            {#            </div>#}
            {#            <div class="form-group">#}
            {#              <input type="text" class="form-control" name="university" placeholder="University">#}
            {#            </div>#}
            {#            <div class="form-group">#}
            {#              <input type="text" class="form-control" name="number" placeholder="Student Number">#}
            {#            </div>#}
            {#            <div class="form-group">#}
            {#              <textarea class="form-control" id="exampleFormControlTextarea1" rows="3" placeholder="Skills"></textarea>#}
            {#            </div>#}
            {#            <button type="submit"  class="btn btn-primary">Submit</button>#}
            {#          </form>#}
        </div>
    </div>
</div>

<footer class="fixed-bottom">
    <div class="container footer-signin">
        <div class="row">
            <div class="col-12 justify-content-center">
                <p style="text-align: center">Copyright 2019 | <a href="">Terms
                    and Conditions</a> applied</p>
            </div>
        </div>
    </div>
</footer>

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
</body>
</html>

templates/users/student-details.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="/static/style.css">
    <title>ANT!</title>
  </head>
  <body>
    <header id="header">
      <div class="container-fluid head">
        <div class="row">
          <div class="col-1"></div>
          <div class="col">
            <img id="logo" class="img-fluid" src="/static/pictures/logo.png" alt="">
            <div class="container">
              <h1 class="display-4" style="margin: 0"><b>Ant</b></h1>
            <p style="margin: 0">Connect Student and Organisations togethers</p>
            </div>
          </div>
          <div class="col">
            <button type="button" class="btn btn-danger home-btn" href="sign_in.html">Log Out</button>
          </div>
          <div class="col-1"></div>
        </div>
      </div>
    </header><!-- /header --> 

    <nav class="navbar sticky-top navbar-light bg-light">
      <div class="container">
        <a href="#" class="">Dashboard</a>
        <a href="#" class="">Applications</a>
        <a href="#" class="">Viewed</a>
        <a href="#" class="">Interested</a>
        <a href="#" class="">Application Applied</a>
        <a href="#" class="">Your Profile</a>
      </div>
    </nav>
    <br>
    <article>
      <div class="container">
        <div class="row">
          <div class="col-3">
            <ul class="list-group">
              <a class="list-group-item active" style="color: white">Categories</a>
              <a class="list-group-item" href="#">SEO</a>
              <a class="list-group-item" href="#">SEM</a>
              <a class="list-group-item" href="#">Social Media Marketing</a>
              <a class="list-group-item" href="#">Student-led Projects</a>
              <a class="list-group-item" href="#">Other</a>
            </ul>
          </div>
          <div class="col justify-content-center">
            <img src="/static/pictures/company.jpg" alt="" style="width: 250px; height: 200px;">
            <br>
            <small>Company Name</small>
            <br>
            <h2>Projects Name</h2>
            <br>
            <p>Projects Description</p>
            <p>
              Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
            </p>
            <br>
            <button class="btn btn-primary btm-sm">Apply</button>
            <button class="btn btn-light btm-sm">Back to Application</button>
            <br>
            <br>
            <h2>About Company</h2>
            <p>
              Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
            </p>
              </div>
            </div>

          </div>
        </div>
      </div>
    </article>

    <footer>
      <div class="container">
        <div class="row">
          <div class="col-12 justify-content-center">
            <p style="text-align: center">Copyright 2019 | <a href="">Terms and Conditions</a> applied</p>
          </div>
        </div>
      </div>
      
    </footer>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>